# Generated by Django 4.2.7 on 2024-03-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='image',
            field=models.ImageField(default='Doc_management\\estudiantes\\images\\DSC_1379.JPG', upload_to='estudiantes/images/'),
            preserve_default=False,
        ),
    ]
