# Generated by Django 5.0.2 on 2024-03-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_management', '0002_estudiante_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='image',
            field=models.ImageField(blank=True, default='Fontan\\Fontan-main\\estudiantes\\images\\default.JPG', null=True, upload_to='estudiantes/images/'),
        ),
    ]
